esphome:
  name: device01
  on_boot:
      priority: 200.0
      then:
        - component.update: eink_display
        - delay: 10s
        - logger.log: "Initial sensor data received: Refreshing display..."
        - script.execute: update_screen

esp32:
  board: esp32dev
  framework:
    type: arduino

# Script for updating screen - Refresh display and publish refresh count and time. (Thanks @paviro!)
script:
  - id: update_screen
    then:
      - component.update: eink_display

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

image:
  - file: "tree.png"
    id: logo
    type: BINARY
    
time:
  - platform: sntp
    id: ntp_time
    timezone: Europe/Paris
    servers: 
    - mafreebox.free.fr
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - component.update: eink_display
sensor:
  - platform: homeassistant
    entity_id: sensor.air_stat_1_temperature
    id: temperature_salon   
    on_value:
      then:
      - component.update: eink_display
  - platform: am2320
    i2c_id: bus_a
    temperature:
      name: "temperature"
      id: temperature
      unit_of_measurement: "°C"
      icon: "mdi:water-percent"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      on_value:
        then:
        - component.update: eink_display
    humidity:
      id: humidity
      name: "humidity"
      unit_of_measurement: "%"
      icon: "mdi:water-percent"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
    update_interval: 60s

binary_sensor:
  - platform: gpio
    internal: true
    name: "Backlight request"
    id: backlight_request
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: backlight
        - delay: 5s
        - switch.turn_off: backlight

switch:
  - platform: gpio
    internal: true
    pin: GPIO12
    name: "backlight"
    id: backlight

# Example configuration entry
font:
  # gfonts://family[@weight]
  - file: "gfonts://Merienda"
    id: font1
    size: 40

i2c:
  - id: bus_a
    sda: GPIO32
    scl: GPIO33
    scan: true

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

display:
  - platform: waveshare_epaper
    id: eink_display
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 1.54inv2
    update_interval: 5s
    full_update_every: 60
    lambda: |-
      it.line(0,100, 200, 100);
      it.line(100, 100, 100, 200);

      it.image(0, 0, id(logo));
      it.strftime(50, 150, id(font1), TextAlign::CENTER, "%H:%M", id(ntp_time).now());
      it.printf(150, 150, id(font1), TextAlign::CENTER, "%.1f°", id(temperature).state);

